version: '3.8'

services:
  mdm-profile-generator:
    image: registry.digitalocean.com/your-registry/ios-mdm-profile-generator:latest
    container_name: mdm-profile-server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - LOG_LEVEL=info
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-*}
    volumes:
      - mdm-poc-logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - mdm-poc-network

  nginx:
    image: nginx:alpine
    container_name: mdm-poc-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deployment/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./deployment/ssl:/etc/nginx/ssl:ro
    depends_on:
      - mdm-profile-generator
    restart: unless-stopped
    networks:
      - mdm-poc-network

volumes:
  mdm-poc-logs:
    driver: local

networks:
  mdm-poc-network:
    driver: bridge 