apiVersion: apps/v1
kind: Deployment
metadata:
  name: mdm-poc
  labels:
    app: mdm-poc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mdm-poc
  template:
    metadata:
      labels:
        app: mdm-poc
    spec:
      containers:
      - name: mdm-poc
        image: registry.digitalocean.com/your-registry/mdm-poc:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: LOG_LEVEL
          value: "info"
        - name: ALLOWED_ORIGINS
          value: "*"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mdm-poc-service
spec:
  selector:
    app: mdm-poc
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer 